# Docker Compose file for elastic_kibana

# Build with:
# docker-compose build elastic_kibana

# Run with:
# docker-compose up

elastic_kibana:
  build: .
  ports:
    - "5601:5601"
    - "9200:9200"
    - "5044:5044"
  volumes: 
    - ./data:/data/
